### PR TITLE
Remove buffertools from dependencies

### LINKED ISSUE #2: buffertools prevent uses of library on Windows
Instead of using buffertools to compare two Buffer, you can use the [Buffer.compare method](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_compare_buf1_buf2)

PR incoming!

### PR DESCRIPTION
**Pull request by GermainBergeron**
fixes #2

### CODE REVIEW

**Comment by GermainBergeron** [comment]
Buffer.compare is available on node >= 4 which explains the failure. I didn't want to modify the tests dependencies

**Comment by remko** [comment]
Thanks for bringing this up, Germain.
If you don't mind, I'll probably add a fallback to a naive Buffer comparison on older Node versions that support it; the dependencies will stay the same.

**Comment by remko** [comment]
Merged

**Comment by GermainBergeron** [comment]
Seems perfect to me, thanks!

**Pull request closed without merging**
